### ISSUE TITLE
Any plans to release the cleaned datasets ?

### ISSUE THREAD

**Issue by rohit-gupta** [facebookresearch/cc_net#1] opened 2019-11-06 18:24 UTC
Pretty much what it says in the title.

**Comment by gwenzek** [comment] 2019-11-06 20:22
We can't release directly the full dataset for legal reasons. The text from websites doesn't belong to Facebook, so Facebook can't distribute it.
But we are distributing a version of the dataset without the text (URL, LID, perplexity) and provide the code to fetch the corresponding text. Let me know if the instructions in the README aren't clear:

https://github.com/facebookresearch/cc_net/blob/master/README.md#reproducing-our-work

**Comment by gwenzek** [comment] 2019-11-12 11:26
Closing, feel free to reopen if I haven't fully answer your question. Thanks.

**Closed** 2019-11-12 11:42 UTC

**Comment by rohit-gupta** [comment] 2019-11-12 17:10
@gwenzek Yes, thank you for the detailed answer !

**Comment by gvskalyan** [comment] 2020-03-17 10:56
Hi @gwenzek , Can the scripts to preprocess, dedupe etc be used for commercial purposes.

**Comment by gwenzek** [comment] 2020-03-19 12:43
Currently all the code is under the Creative Common "Attribution-NonCommercial 4.0 International" license, as specified by the [LICENSE](https://github.com/facebookresearch/cc_net/blob/master/LICENSE) file.

**Comment by gwenzek** [comment] 2020-10-27 21:26
@gvskalyan Code has been relicensed to MIT: 242e10d
